export const LOCATION_UPDATED = 'LOCATION_UPDATED';
export const WILD_POKEMON_ADDED = 'WILD_POKEMON_ADDED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
